title: Communication responsable

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "guidelines"
    values:
      layout: "guideline"

  -
    scope:
      path: ""
      type: "themes"
    values:
      layout: "theme"

collections:
  pages:
    output: true
  guidelines:
    output: true
    permalink: /recommandations/:name
  themes:
    output: true
    permalink: /themes/:name
